    -- Dodawanie unikalnych danych do tabeli Author
    INSERT INTO Author (FirstName, LastName)
    VALUES ('Fyodor', 'Dostoevsky'),
           ('Margaret', 'Mitchell'),
           ('Franz', 'Kafka'),
           ('Louisa', 'May Alcott'),
           ('Leo', 'Tolstoy'),
           ('J.R.R.', 'Tolkien'),
           ('E.M.', 'Forster'),
           ('Ray', 'Bradbury'),
           ('Oscar', 'Wilde'),
           ('Terry', 'Goodkind'),
           ('Margaret', 'Atwood'),
           ('Albert', 'Camus'),
           ('Yann', 'Martel'),
           ('John', 'Green'),
           ('Kurt', 'Vonnegut'),
           ('Ernest', 'Hemingway'),
           ('Aldous', 'Huxley'),
           ('David', 'Foster Wallace'),
           ('Gabriel', 'García Márquez'),
           ('Miguel de', 'Cervantes'),
           ('J.D.', 'Salinger'),
           ('H.G.', 'Wells'),
           ('John', 'Steinbeck'),
           ('Anne', 'Frank'),
           ('Arthur', 'Conan Doyle'),
           ('Khaled', 'Hosseini'),
           ('Sylvia', 'Plath'),
           ('Philip K.', 'Dick'),
           ('Jane', 'Austen'),
           ('Ken', 'Kesey'),
           ('Emily', 'Brontë'),
           ('Ayn', 'Rand'),
           ('Kazuo', 'Ishiguro'),
           ('Mary', 'Shelley'),
           ('Gustave', 'Flaubert'),
           ('Hermann', 'Hesse'),
           ('Toni', 'Morrison'),
           ('Jack', 'Kerouac'),
           ('Mikhail', 'Bulgakov'),
           ('Ken', 'Follett'),
           ('Mario', 'Puzo'),
           ('J.K.', 'Rowling'),
           ('Harper', 'Lee'),
           ('Philip', 'Pullman'),
           ('John', 'Kennedy Toole'),
           ('Orson', 'Scott Card'),
           ('Neil', 'Gaiman'),
           ('Haruki', 'Murakami'),
           ('George', 'Orwell'),
           ('Terry', 'Pratchett'),
           ('C.S.', 'Lewis'),
           ('George R.R.', 'Martin'),
           ('Daphne', 'Du Maurier'),
           ('Anthony', 'Burgess'),
           ('Mark', 'Twain'),
           ('Lewis', 'Carroll'),
           ('William', 'Golding'),
           ('F. Scott', 'Fitzgerald'),
           ('Herman', 'Melville'),
           ('-', 'Homer'),
           ('-', 'Virgil'),
           ('-', 'Euripides'),
           ('-', 'Aeschylus'),
           ('Friedrich', 'Nietzsche'),
           ('James', 'Joyce'),
           ('William', 'Shakespeare'),
           ('Herman', 'Hesse');