-- Dodawanie unikalnych danych do tabeli Genre
INSERT INTO Genre (GenreName)
VALUES ('Classic'),
       ('Historical Fiction'),
       ('Fantasy'),
       ('Philosophical Fiction'),
       ('Literary Fiction'),
       ('Young Adult'),
       ('Science Fiction'),
       ('Utopian'),
       ('Postmodern'),
       ('Short Stories'),
       ('Nonfiction'),
       ('Magical Realism'),
       ('Satire'),
       ('Crime'),
       ('Humor'),
       ('Dystopian'),
       ('Gothic'),
       ('Philosophy'),
       ('Modernist'),
       ('Existentialism'),
       ('Romance'),
       ('Comedy'),
       ('Mystery'),
       ('Adventure'),
       ('Contemporary'),
       ('Magic Realism'),
       ('Fiction'),
       ('History'),
       ('Supernatural'),
       ('Mythology'),
       ('Political Satire'),
       ('War'),
       ('Drama'),
       ('Epic'),
       ('Tragedy');