-- Dodawanie unikalnych danych do tabeli Publisher
INSERT INTO Publisher (PublisherName, Address, Country)
VALUES ('Penguin Classics', '80 Strand, London', 'England'),
       ('Grand Central Publishing', '1290 Avenue of the Americas, New York, NY', 'USA'),
       ('Puffin Books', '345 Hudson Street, New York, NY', 'USA'),
       ('Mariner Books', '222 Berkeley Street, Boston, MA', 'USA'),
       ('William Morrow Paperbacks', '195 Broadway, New York, NY', 'USA'),
       ('Dover Publications', '31 East 2nd Street, Mineola, NY', 'USA'),
       ('Tor Books', '175 Fifth Avenue, New York, NY', 'USA'),
       ('Anchor Books', '1745 Broadway, New York, NY', 'USA'),
       ('Vintage International', '1745 Broadway, New York, NY', 'USA'),
       ('Speak', '1745 Broadway, New York, NY', 'USA'),
       ('Dial Press Trade Paperback', '1745 Broadway, New York, NY', 'USA'),
       ('Scribner', '1230 Avenue of the Americas, New York, NY', 'USA'),
       ('Harper Perennial Modern Classics', '195 Broadway, New York, NY', 'USA'),
       ('Back Bay Books', '1745 Broadway, New York, NY', 'USA'),
       ('Vintage', '1745 Broadway, New York, NY', 'USA'),
       ('Little, Brown and Company', '1290 Avenue of the Americas, New York, NY', 'USA'),
       ('Penguin Books', '80 Strand, London', 'England'),
       ('Bantam Books', '1745 Broadway, New York, NY', 'USA'),
       ('Riverhead Books', '1745 Broadway, New York, NY', 'USA'),
       ('Del Rey', '1745 Broadway, New York, NY', 'USA'),
       ('Signet', '1745 Broadway, New York, NY', 'USA'),
       ('Faber & Faber', 'Bloomsbury House, 74-77 Great Russell Street, London', 'England'),
       ('Vintage Espanol', '1745 Broadway, New York, NY', 'USA'),
       ('Houghton Mifflin Harcourt', '222 Berkeley Street, Boston, MA', 'USA'),
       ('Dutton Books', '1745 Broadway, New York, NY', 'USA'),
       ('Picador', '175 Fifth Avenue, New York, NY', 'USA'),
       ('Simon & Schuster', '1230 Avenue of the Americas, New York, NY', 'USA'),
       ('New American Library', '1745 Broadway, New York, NY', 'USA'),
       ('Bloomsbury Publishing', '50 Bedford Square, London', 'England'),
       ('Harper', '195 Broadway, New York, NY', 'USA'),
       ('Knopf Books for Young Readers', '1745 Broadway, New York, NY', 'USA'),
       ('Grove Press', '1745 Broadway, New York, NY', 'USA'),
       ('Nan A. Talese', '1745 Broadway, New York, NY', 'USA'),
       ('William Morrow', '195 Broadway, New York, NY', 'USA'),
       ('Signet Classics', '1745 Broadway, New York, NY', 'USA'),
       ('Oxford University Press', 'Great Clarendon Street, Oxford', 'England'),
       ('HarperTorch', '195 Broadway, New York, NY', 'USA'),
       ('HarperCollins', '195 Broadway, New York, NY', 'USA'),
       ('Bantam', '1745 Broadway, New York, NY', 'USA'),
       ('W. W. Norton & Company', '500 Fifth Avenue, New York, NY', 'USA'),
       ('Anchor', '1745 Broadway, New York, NY', 'USA'),
       ('NAL Trade', '1745 Broadway, New York, NY', 'USA');
